name: Bon Aqua Computer Club
permalink: :year/:month/:day
baseurl: ""

# Your blog's start year and this year, showed in the footer left
# start is optional
start: 2021
now: 2022
 
future: true
# Social links showed in the footer
# You just need modify the nickname of github and twitter
link:
  email : andrew@grathwohl.me
  github : agrathwohl
    #twitter : yourname

# Links in the navigation, you can modify both link name and link url
nav:
   Home: "/"
   About: "/about"

   
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed
